@startuml
hide empty description

[*] -d-> Dashboard

Dashboard --> SelectedProject : SelectProject\n[nº projects > 0]

SelectedProject --> SelectedProject : SelectProject
SelectedProject --> EditColor : EditProjectColor

EditColor --> Dashboard : SelectColor
EditColor --> Dashboard : RemoveColor
EditColor --> Dashboard : CancelColor
EditColor --> CustomColor : GoCustomColor

CustomColor --> Dashboard : SelectColor
CustomColor --> Dashboard : CancelColor
CustomColor --> CustomColor : ResetColor
@enduml
