@startuml
hide empty description

state EndState #brown

[*] --> Dashboard

Dashboard --> MinimizedToTray : Minimize
Dashboard --> EndState : Close
Dashboard --> AddProject : Add

AddProject --> MinimizedToTrayAdd : Minimize
AddProject --> EndState : Close
AddProject --> Dashboard : ConfirmNameChange
AddProject --> Dashboard : CancelNameChange
AddProject --> AddProject : Add

MinimizedToTrayAdd --> AddProject : Maximize
MinimizedToTrayAdd --> EndState : Close

MinimizedToTray --> Dashboard : Maximize
MinimizedToTray --> EndState : Close

@enduml
