@startuml
hide empty description

[*] -d-> Dashboard

Dashboard --> [*] : Close
Dashboard --> EditColor : EditColor

EditColor --> Dashboard : SelectColor
EditColor --> Dashboard : RemoveColor
EditColor --> Dashboard : CancelColor
EditColor --> CustomColor : GoCustomColor

CustomColor --> Dashboard : SelectColor
CustomColor --> Dashboard : CancelColor
CustomColor --> CustomColor : ResetColor
@enduml
