@startuml
hide empty description

[*] --> Dashboard

Dashboard -d-> CreateProject : AddProject

CreateProject -d-> EditName : EditProjectName

EditName -u-> CreateProject : AddProject
EditName -d-> SaveName : ConfirmNameChange
EditName -u-> Dashboard : CancelNameChange

SaveName -u-> Dashboard : BackToIdle

@enduml
