@startuml
hide empty description

[*] -d-> Dashboard

Dashboard --> SelectedProject : SelectProject\n[nº projects > 0]

SelectedProject --> SelectedProject : SelectProject
SelectedProject --> EditColor : ClickEditColorButton

EditColor --> SelectedProject : CancelColorEdit
EditColor --> SaveColor : SelectColor
EditColor --> SaveColor : RemoveColor
EditColor --> CustomColor : OpenCustomColorMenu

CustomColor --> SelectedProject : CancelColorEdit
CustomColor --> SaveColor : SelectColor
CustomColor --> CustomColor : ResetColor

SaveColor --> SelectedProject : BackToIdle
@enduml
