@startuml
hide empty description

[*] --> Dashboard

Dashboard --> CreateProject : AddProject

CreateProject --> EditName : EditProjectName

EditName --> Dashboard : ConfirmNameChange
EditName --> Dashboard : CancelNameChange

@enduml
