@startuml
hide empty description

[*] --> Dashboard

Dashboard --> SelectedProject : SelectProject\n[nº projects > 0]

SelectedProject --> SelectedProject : SelectProject
SelectedProject --> DeleteProject : ClickDeleteButton

DeleteProject --> Dashboard : BackToIdle

@enduml
