@startuml
hide empty description

[*] --> Dashboard

Dashboard --> SelectedProject : SelectProject\n[nº projects > 0]

SelectedProject --> SelectedProject : SelectProject
SelectedProject --> PlayingProject : PlayProject\n[selected project is not playing]

PlayingProject --> PlayingProject : PlayProject\n[selected project is not playing]
PlayingProject --> SelectedProject : PauseProject\n[selected project is playing]

@enduml
