@startuml
skinparam linetype polyline

[Dashboard 0] -d-> [SelectedProject 0] 

[SelectedProject 0] -d-> [SelectedProject 1] 
[SelectedProject 0] -d-> [DeleteProject 0] 

[DeleteProject 0] -d-> [Dashboard 1] 

@enduml