@startuml
skinparam linetype polyline
[Dashboard 0] -d-> [EditColor 0] : EditColor

[EditColor 0] -d-> [Dashboard 2] : SelectColor
[EditColor 0] -d-> [Dashboard 3] : RemoveColor
[EditColor 0] -d-> [Dashboard 4] : CancelColor
[EditColor 0] -d-> [CustomColor 0] : GoCustomColor

[CustomColor 0] -d-> [Dashboard 5] : SelectColor
[CustomColor 0] -d-> [Dashboard 6] : CancelColor
[CustomColor 0] -d-> [CustomColor 1] : ResetColor
@enduml