@startuml
skinparam linetype polyline

[Dashboard 0] -d-> [CreateProject 0] : AddProject

[CreateProject 0] -d-> [EditName 0] : EditProjectName

[EditName 0] -d-> [Dashboard 1] : ConfirmNameChange
[EditName 0] -d-> [Dashboard 2] : CancelNameChange
[EditName 0] -d-> [CreateProject 1] : AddProject

@enduml
