@startuml
skinparam linetype polyline
[Dashboard 0] -d-> [SelectedProject 0]

[SelectedProject 0] -d-> [SelectedProject 1]
[SelectedProject 0] -d-> [EditColor 0]

[EditColor 0] -d-> [SelectedProject 2]
[EditColor 0] -d-> [CustomColor 0]
[EditColor 0] -d-> [SaveColor 0]
[EditColor 0] -d-> [SaveColor 1]

[CustomColor 0] -d-> [SelectedProject 3]
[CustomColor 0] -d-> [CustomColor 1]
[CustomColor 0] -d-> [SaveColor 2]

[SaveColor 0] -d-> [SelectedProject 4]

@enduml
