@startuml
skinparam linetype polyline

[Dashboard 0] -d-> [CreateProject 0]

[CreateProject 0] -d-> [EditName 0]

[EditName 0] -d-> [Dashboard 1]
[EditName 0] -d-> [Dashboard 2]
[EditName 0] -d-> [CreateProject 1]

@enduml
